//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC
    {
        public int IdBC { get; set; }
        public string NumBc { get; set; }
        public string Destination { get; set; }
        public string DelaiExecution { get; set; }
        public System.DateTime DateBC { get; set; }
    
        public virtual FE InfoFE { get; set; }
        public virtual Morasse InfoMorasse { get; set; }
        public virtual PVJ InfoPVJ { get; set; }
    }
}
