//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa
{
    using System;
    using System.Collections.Generic;
    
    public partial class FE
    {
        public int IdFE { get; set; }
        public int CreditsBudgetaires { get; set; }
        public int DepensesEngagees { get; set; }
        public int Disponible { get; set; }
        public int EngagementDepensesPropose { get; set; }
    
        public virtual OI InfoOI { get; set; }
        public virtual BC InfoBC { get; set; }
    }
}
