//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fournisseur()
        {
            this.ListPVJ1 = new HashSet<PVJ>();
            this.ListModeleDevis = new HashSet<ModeleDevis>();
            this.ListConsultation = new HashSet<Consultation>();
            this.ListPVJ2 = new HashSet<PVJ>();
        }
    
        public int IdFournisseur { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public int RC_n { get; set; }
        public string Patente_n { get; set; }
        public int IF_n { get; set; }
        public int CNSS_n { get; set; }
        public string Compte_bancaire_n { get; set; }
        public string ICE { get; set; }
        public string Ville { get; set; }
        public string Banque { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PVJ> ListPVJ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModeleDevis> ListModeleDevis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultation> ListConsultation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PVJ> ListPVJ2 { get; set; }
    }
}
