//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa
{
    using System;
    using System.Collections.Generic;
    
    public partial class LettreConsultation
    {
        public int IdLettre { get; set; }
        public System.DateTime DateLettre { get; set; }
        public System.DateTime DateDelai { get; set; }
    
        public virtual Consultation Consultation { get; set; }
    }
}
