//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa
{
    using System;
    using System.Collections.Generic;
    
    public partial class OI
    {
        public int IdOI { get; set; }
        public string NumOi { get; set; }
        public System.DateTime DateOI { get; set; }
        public string NumCompteDebit { get; set; }
        public string VisaControle { get; set; }
        public string VisaCsrs { get; set; }
        public System.DateTime DatePaiement { get; set; }
        public string VisaSordonnateur { get; set; }
        public string VisaTresorierPayeur { get; set; }
    
        public virtual PVR InfoPVR { get; set; }
        public virtual FE InfoFE { get; set; }
        public virtual OP InfoOP { get; set; }
    }
}
