//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnssaModelContainer4 : DbContext
    {
        public OnssaModelContainer4()
            : base("name=OnssaModelContainer4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fournisseur> FournisseurSet { get; set; }
        public virtual DbSet<Commission> CommissionSet { get; set; }
        public virtual DbSet<Consultation> ConsultationSet { get; set; }
        public virtual DbSet<PVJ> PVJSet { get; set; }
        public virtual DbSet<ModeleDevis> ModeleDevisSet { get; set; }
        public virtual DbSet<Produit> ProduitSet { get; set; }
        public virtual DbSet<PVR> PVRSet { get; set; }
        public virtual DbSet<BC> BCSet { get; set; }
        public virtual DbSet<FE> FESet { get; set; }
        public virtual DbSet<Morasse> MorasseSet { get; set; }
        public virtual DbSet<OI> OISet { get; set; }
        public virtual DbSet<OP> OPSet { get; set; }
        public virtual DbSet<OV> OVSet { get; set; }
        public virtual DbSet<GestionCompte> GestionCompteSet { get; set; }
    }
}
