//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Onssa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("workstation id=OnssaProjet.mssql.somee.com;packet size=4096;user id=zakarm_SQLLog" +
            "in_1;pwd=g9b9ychmvx;data source=OnssaProjet.mssql.somee.com;persist security inf" +
            "o=False;initial catalog=OnssaProjet")]
        public string Onssa_ProjetConnectionString {
            get {
                return ((string)(this["Onssa_ProjetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("workstation id=OnssaProjet.mssql.somee.com;packet size=4096;user id=zakarm_SQLLog" +
            "in_1;pwd=g9b9ychmvx;data source=OnssaProjet.mssql.somee.com;persist security inf" +
            "o=False;initial catalog=OnssaProjet")]
        public string Onssa_ProjetConnectionString1 {
            get {
                return ((string)(this["Onssa_ProjetConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("workstation id=OnssaProjet.mssql.somee.com;packet size=4096;user id=zakarm_SQLLog" +
            "in_1;pwd=g9b9ychmvx;data source=OnssaProjet.mssql.somee.com;persist security inf" +
            "o=False;initial catalog=OnssaProjet")]
        public string Onssa_DbConnectionString {
            get {
                return ((string)(this["Onssa_DbConnectionString"]));
            }
        }
    }
}
